[package]
name = "modern-ovgu-fma-polylux"
version = "0.1.0"
entrypoint = "ovgu-fma-polylux-theme.typ"
license = "MIT-0"
description = "Unofficial template for creating presentations with Polylux in the style of the Faculty of Mathematics at the Otto-von-Guericke-University Magdeburg."

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "images/thumbnail.png"