[package]
name = "modern-ovgu-fma-polylux"
version = "0.1.0"
license = "MIT-0"
#description = "Unofficial template for creating presentations with Polylux in the style of the Faculty of Mathematics at the Otto-von-Guericke-University Magdeburg."
#categories = ["presentation"]
#keywords = ["presentation", "polylux", "FMA", "Faculty of Mathematics, "university", "OVGU", "Magdeburg", "Otto-von-Guericke Universität"]
author = ["Jonas Danker"]
entrypoint = "modern-ovgu-fma-polylux.typ"
exclude = [
    "*.pdf",
    "images"
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "images/thumbnail.png"